services:
  web:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --proxy-headers --reload
    volumes:
      - ./app:/app
    env_file:
      - ./config/.env.dev
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/login"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

  mongo:
    image: mongo:6
    container_name: tgfp-mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mongo-data-dev: