services:
  tgfp-mongodb:
    image: mongo:6
    env_file:
      - stack.env
    restart: unless-stopped
    container_name: tgfp-mongodb
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - tgfp-db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/ --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  tgfp-web:
    image: johnofcamas/tgfp-web:latest
    container_name: tgfp-web
    restart: unless-stopped
    command: gunicorn -b 0.0.0.0:$WEB_PORT app:app
    env_file:
      - stack.env
    ports:
      - "6701:6701"
    depends_on:
      tgfp-mongodb:
        condition: service_started
volumes:
  tgfp-db:
    external: true
