"""added field uniqueness

Revision ID: 1885e311300d
Revises: 9ff5e4af6bbc
Create Date: 2025-08-30 10:34:14.129601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1885e311300d'
down_revision: Union[str, Sequence[str], None] = '9ff5e4af6bbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_tgfp_nfl_game_id'), table_name='game')
    op.create_index(op.f('ix_game_tgfp_nfl_game_id'), 'game', ['tgfp_nfl_game_id'], unique=True)
    op.create_index(op.f('ix_player_email'), 'player', ['email'], unique=True)
    op.create_index(op.f('ix_team_tgfp_nfl_team_id'), 'team', ['tgfp_nfl_team_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_tgfp_nfl_team_id'), table_name='team')
    op.drop_index(op.f('ix_player_email'), table_name='player')
    op.drop_index(op.f('ix_game_tgfp_nfl_game_id'), table_name='game')
    op.create_index(op.f('ix_game_tgfp_nfl_game_id'), 'game', ['tgfp_nfl_game_id'], unique=False)
    # ### end Alembic commands ###
