"""sync models

Revision ID: 1d182830440b
Revises: 55ffa03ea206
Create Date: 2026-01-07 14:01:13.431256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1d182830440b"
down_revision: Union[str, Sequence[str], None] = "55ffa03ea206"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "game",
        sa.Column("season_type", sa.Integer(), nullable=False, server_default="2"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("game", "season_type")
    # ### end Alembic commands ###
