"""add season_type to game playeraward and playergamepick

Revision ID: 20f54c1632bc
Revises: 55ffa03ea206
Create Date: 2026-01-08 18:14:49.132325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "20f54c1632bc"
down_revision: Union[str, Sequence[str], None] = "55ffa03ea206"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add season_type columns with server_default for existing data
    op.add_column(
        "game",
        sa.Column(
            "season_type", sa.Integer(), nullable=False, server_default=sa.text("2")
        ),
    )
    op.add_column(
        "playeraward",
        sa.Column(
            "season_type", sa.Integer(), nullable=False, server_default=sa.text("2")
        ),
    )
    op.add_column(
        "playergamepick",
        sa.Column(
            "season_type", sa.Integer(), nullable=False, server_default=sa.text("2")
        ),
    )

    # Add player stats columns with server_default for existing data
    op.add_column(
        "player",
        sa.Column("wins", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    op.add_column(
        "player",
        sa.Column("losses", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    op.add_column(
        "player",
        sa.Column("bonus", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )

    # Update unique constraint to include season_type
    op.drop_index(
        op.f("uq_one_lock_per_week"),
        table_name="playergamepick",
        postgresql_where="(is_lock = true)",
    )
    op.create_index(
        "uq_one_lock_per_week",
        "playergamepick",
        ["player_id", "season", "season_type", "week_no"],
        unique=True,
        postgresql_where=sa.text("is_lock = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_one_lock_per_week",
        table_name="playergamepick",
        postgresql_where=sa.text("is_lock = true"),
    )
    op.create_index(
        op.f("uq_one_lock_per_week"),
        "playergamepick",
        ["player_id", "season", "week_no"],
        unique=True,
        postgresql_where="(is_lock = true)",
    )
    op.drop_column("playergamepick", "season_type")
    op.drop_column("playeraward", "season_type")
    op.drop_column("player", "bonus")
    op.drop_column("player", "losses")
    op.drop_column("player", "wins")
    op.drop_column("game", "season_type")
    # ### end Alembic commands ###
