"""sync models

Revision ID: 266172a6427b
Revises: ae212af0add3
Create Date: 2026-01-07 16:54:40.162895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "266172a6427b"
down_revision: Union[str, Sequence[str], None] = "ae212af0add3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "game",
        "season_type",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "playeraward",
        "season_type",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "playergamepick",
        "season_type",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "playergamepick",
        "season_type",
        existing_type=sa.INTEGER(),
        server_default=sa.text("2"),
        existing_nullable=False,
    )
    op.alter_column(
        "playeraward",
        "season_type",
        existing_type=sa.INTEGER(),
        server_default=sa.text("2"),
        existing_nullable=False,
    )
    op.alter_column(
        "game",
        "season_type",
        existing_type=sa.INTEGER(),
        server_default=sa.text("2"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
