"""sync models

Revision ID: 2738a86e73ab
Revises: 1885e311300d
Create Date: 2025-09-02 16:30:00.700284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2738a86e73ab'
down_revision: Union[str, Sequence[str], None] = '1885e311300d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playergamepick', 'awarded_points')
    op.drop_column('playergamepick', 'is_win')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playergamepick', sa.Column('is_win', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('playergamepick', sa.Column('awarded_points', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
