"""add season_type to uq_one_lock_per_week constraint

Revision ID: 370d33fc3d99
Revises: 61324ee1ee27
Create Date: 2026-01-08 15:39:52.824787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '370d33fc3d99'
down_revision: Union[str, Sequence[str], None] = '61324ee1ee27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_one_lock_per_week'), table_name='playergamepick', postgresql_where='(is_lock = true)')
    op.create_index('uq_one_lock_per_week', 'playergamepick', ['player_id', 'season', 'season_type', 'week_no'], unique=True, postgresql_where=sa.text('is_lock = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_lock_per_week', table_name='playergamepick', postgresql_where=sa.text('is_lock = true'))
    op.create_index(op.f('uq_one_lock_per_week'), 'playergamepick', ['player_id', 'season', 'week_no'], unique=True, postgresql_where='(is_lock = true)')
    # ### end Alembic commands ###
