"""Update Award

Revision ID: 3ee0b50250b7
Revises: fd1399e5799e
Create Date: 2025-09-16 09:21:17.083275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3ee0b50250b7"
down_revision: Union[str, Sequence[str], None] = "fd1399e5799e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "award", sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.create_index(op.f("ix_award_slug"), "award", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_award_slug"), table_name="award")
    op.drop_column("award", "slug")
    # ### end Alembic commands ###
