"""Added award notificiation field

Revision ID: 55ffa03ea206
Revises: 3ee0b50250b7
Create Date: 2025-09-17 10:45:17.762107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55ffa03ea206'
down_revision: Union[str, Sequence[str], None] = '3ee0b50250b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playeraward', sa.Column('notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playeraward', 'notified_at')
    # ### end Alembic commands ###
