"""sync models

Revision ID: 625c1208cbe0
Revises: 266172a6427b
Create Date: 2026-01-08 13:47:17.845310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '625c1208cbe0'
down_revision: Union[str, Sequence[str], None] = '266172a6427b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('wins', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('player', sa.Column('losses', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('player', sa.Column('bonus', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'bonus')
    op.drop_column('player', 'losses')
    op.drop_column('player', 'wins')
    # ### end Alembic commands ###
