"""Add Player Awards

Revision ID: 94f461a2909e
Revises: 2738a86e73ab
Create Date: 2025-09-11 17:04:26.306266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '94f461a2909e'
down_revision: Union[str, Sequence[str], None] = '2738a86e73ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('point_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_award_name'), 'award', ['name'], unique=True)
    op.create_table('playeraward',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['award.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'award_id', 'season', 'week_no', name='uq_playeraward_player_award_week')
    )
    op.create_index(op.f('ix_playeraward_award_id'), 'playeraward', ['award_id'], unique=False)
    op.create_index(op.f('ix_playeraward_player_id'), 'playeraward', ['player_id'], unique=False)
    op.create_index(op.f('ix_playeraward_season'), 'playeraward', ['season'], unique=False)
    op.create_index(op.f('ix_playeraward_week_no'), 'playeraward', ['week_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playeraward_week_no'), table_name='playeraward')
    op.drop_index(op.f('ix_playeraward_season'), table_name='playeraward')
    op.drop_index(op.f('ix_playeraward_player_id'), table_name='playeraward')
    op.drop_index(op.f('ix_playeraward_award_id'), table_name='playeraward')
    op.drop_table('playeraward')
    op.drop_index(op.f('ix_award_name'), table_name='award')
    op.drop_table('award')
    # ### end Alembic commands ###
