"""sync models

Revision ID: ae212af0add3
Revises: 1d182830440b
Create Date: 2026-01-07 16:51:32.351827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ae212af0add3"
down_revision: Union[str, Sequence[str], None] = "1d182830440b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "playeraward",
        sa.Column("season_type", sa.Integer(), nullable=False, server_default="2"),
    )
    op.add_column(
        "playergamepick",
        sa.Column("season_type", sa.Integer(), nullable=False, server_default="2"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playergamepick", "season_type")
    op.drop_column("playeraward", "season_type")
    # ### end Alembic commands ###
