"""sync models

Revision ID: fd1399e5799e
Revises: 94f461a2909e
Create Date: 2025-09-13 16:04:06.110915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd1399e5799e"
down_revision: Union[str, Sequence[str], None] = "94f461a2909e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playeraward", sa.Column("game_id", sa.Integer(), nullable=True))
    op.drop_constraint(
        op.f("uq_playeraward_player_award_week"), "playeraward", type_="unique"
    )
    op.create_unique_constraint(
        "uq_playeraward_player_award_week",
        "playeraward",
        ["player_id", "award_id", "season", "week_no", "game_id"],
    )
    op.create_index(
        op.f("ix_playeraward_game_id"), "playeraward", ["game_id"], unique=False
    )
    op.create_foreign_key(None, "playeraward", "game", ["game_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "playeraward", type_="foreignkey")
    op.drop_index(op.f("ix_playeraward_game_id"), table_name="playeraward")
    op.drop_constraint(
        "uq_playeraward_player_award_week", "playeraward", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_playeraward_player_award_week"),
        "playeraward",
        ["player_id", "award_id", "season", "week_no"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("playeraward", "game_id")
    # ### end Alembic commands ###
