id: $flow_id
namespace: $namespace
tasks:
  - id: update_game_loop
    type: io.kestra.plugin.scripts.python.Script
    script: |
      import requests
      import time
      requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)

      game_status = 'STATUS_SCHEDULED'
      while game_status != 'STATUS_FINAL':
        response = requests.get(
            url=$uri,
            timeout=10,
            headers={
                "Authorization": "Bearer {{ secret('TGFP_API_TOKEN') }}",
            },
        )
        game = response.json()
        print(game)
        game_status = game['game_status']
        time.sleep(5)

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    timezone: US/Pacific
    cron: "$cron"

