name: Docker Image CI

on:
  push:
    tags: [ 'v*']
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token:  ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      -
        name: Load Docker Credentials
        uses: 1password/load-secrets-action@v1
        with:
            # Export loaded secrets as environment variables
          export-env: true
        env:
          DOCKERHUB_TOKEN: op://secrets/DOCKER_HUB_ACCESS_TOKEN/credential
          DOCKERHUB_USERNAME: op://secrets/DOCKER_HUB_ACCESS_TOKEN/username
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/tgfp-web
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}