name: Docker Image CI

on:
  push:
    tags: [ 'v*']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Load secret
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DOCKER_HUB_ACCESS_TOKEN: op://secrets/DOCKER_HUB_ACCESS_TOKEN/credential
          DOCKER_HUB_USERNAME: op://secrets/DOCKER_HUB_ACCESS_TOKEN/username
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: $DOCKER_HUB_USERNAME/tgfp-web
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}